In [2]:
import numpy as np

def generar_matrices(n_matrices, condicion="pares"):
    """
    Genera un número 'n' de matrices de 4x4 bajo una condición específica.
    """
    matrices = [] 
    
    for i in range(n_matrices):
        if condicion == "pares":
            matriz = np.random.randint(1, 51, size=(4, 4)) * 2
        elif condicion == "impares":
            matriz = np.random.randint(0, 50, size=(4, 4)) * 2 + 1
        elif condicion == "multiplos_de_5":
            matriz = np.random.randint(1, 21, size=(4, 4)) * 5
        else:
            matriz = np.random.randint(1, 101, size=(4, 4))
            
        matrices.append(matriz)
        
    return matrices

#condiciones
cantidad = 8               
tipo_condicion = "pares"   

#se generan matrices
mis_matrices = generar_matrices(cantidad, tipo_condicion)

print(f"Generando {cantidad} matrices de 4x4 con la condición: {tipo_condicion}\n")

for i, matriz in enumerate(mis_matrices):
    print(f"--- Matriz {i + 1} ---")
    print(matriz)
    print("")


Generando 8 matrices de 4x4 con la condición: pares

--- Matriz 1 ---
[[ 32  60  22  46]
 [  2  18  50  62]
 [ 30 100  12  10]
 [ 52  94  90  62]]

--- Matriz 2 ---
[[100  56  54  84]
 [ 58  58  44  42]
 [ 90  30  68  90]
 [ 30   6  18  74]]

--- Matriz 3 ---
[[ 98  40  34  12]
 [ 48  46  38 100]
 [ 22  46  40  86]
 [ 34  40  58   4]]

--- Matriz 4 ---
[[38 16 22 70]
 [94 78 30 56]
 [32 74 24 60]
 [24 34 54 86]]

--- Matriz 5 ---
[[70 40 24 84]
 [ 6 22 18 16]
 [94 44 64 68]
 [98 12 70 74]]

--- Matriz 6 ---
[[24 28 24 40]
 [ 6 40 76 30]
 [66 14 40 98]
 [60 32 18 70]]

--- Matriz 7 ---
[[ 34  98  20  60]
 [100  88  60  86]
 [ 32  66  54  42]
 [  2   8   2  68]]

--- Matriz 8 ---
[[100  14  68  14]
 [ 30  64  44  48]
 [ 16  82  66  68]
 [ 30  66  20  46]]

