In [11]:

import numpy as np

class primmeraclase:    
    def __init__(self, factorp):     
        self.factor = factorp     
        
    def fabricar_matriz(self):
        matriz_base = np.zeros([4,4]) 
        
        for fila in range(4): 
    
            matriz_base[fila, :] = np.linspace((fila + 1) * self.factor, ((fila + 1) * self.factor) + 18, 4)
            
        return matriz_base

class ApilamientoV:
    def __init__(self):
        self.coleccion_matrices = []
        
    def ejecucionmatrices(self, total_matrices):
        self.coleccion_matrices = [] 
        

        for num in range(2, (total_matrices * 2) + 2, 2):
   
            primmer = primmeraclase(num) 
            nueva_matriz = primmer.fabricar_matriz()
            
            self.coleccion_matrices.append(nueva_matriz)
            
        print(f"matrices {total_matrices} generadas")
        
   
        bloque_final = np.vstack(self.coleccion_matrices)
        return bloque_final

Deberfinal = ApilamientoV()

resultado_unico = Deberfinal.ejecucionmatrices(4)

print("\nMatrices")
print(resultado_unico)

matrices 4 generadas

Matrices
[[ 2.  8. 14. 20.]
 [ 4. 10. 16. 22.]
 [ 6. 12. 18. 24.]
 [ 8. 14. 20. 26.]
 [ 4. 10. 16. 22.]
 [ 8. 14. 20. 26.]
 [12. 18. 24. 30.]
 [16. 22. 28. 34.]
 [ 6. 12. 18. 24.]
 [12. 18. 24. 30.]
 [18. 24. 30. 36.]
 [24. 30. 36. 42.]
 [ 8. 14. 20. 26.]
 [16. 22. 28. 34.]
 [24. 30. 36. 42.]
 [32. 38. 44. 50.]]
